'use client';

import React from 'react';
import { AnimatePresence } from 'framer-motion';
import { Inter } from 'next/font/google';
import { ThemeProvider } from 'styled-components';

import { lightTheme } from '../../Components/Themes';
import SoundBar from '../../Elements/Sound';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: {
  children: React.ReactNode;
}) => (
  <html lang="en">
    <body className={inter.className}>
      <ThemeProvider theme={lightTheme}>
        <SoundBar />
        <AnimatePresence>{children}</AnimatePresence>
      </ThemeProvider>
    </body>
  </html>
);
export default RootLayout;
