#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Set up colors using tput
GREEN="$(tput setaf 2)"
RED="$(tput setaf 1)"
NC="$(tput sgr0)" # No Color

# Run the Prettier check
echo "Running Prettier check..."
npm run check-format

# If the Prettier check fails, exit the script with an error
if [ $? -ne 0 ]; then
    echo "${RED}Prettier check failed. Please correct any style errors and try again.${NC}"
    exit 1
fi
echo "${GREEN}Prettier check passed.${NC}"

# Run the ESLint check
echo "Running ESLint check..."
npm run check-lint

# If the ESLint check fails, exit the script with an error
if [ $? -ne 0 ]; then
    echo "${RED}ESLint check failed. Please correct any lint errors and try again.${NC}"
    exit 1
fi
echo "${GREEN}ESLint check passed.${NC}"

# Run the TypeScript check
echo "Running TypeScript check..."
npm run check-types

# If the TypeScript check fails, exit the script with an error
if [ $? -ne 0 ]; then
    echo "${RED}TypeScript check failed. Please correct any type errors and try again.${NC}"
    exit 1
fi
echo "${GREEN}TypeScript check passed.${NC}"

# If everything passes, build the project
echo "All checks passed. Building the project..."
npm run build

# If the build fails, exit the script with an error
if [ $? -ne 0 ]; then
    echo "${RED}Build failed. Please correct any build errors and try again.${NC}"
    exit 1
fi

echo "${GREEN}Pre-commit checks and build completed successfully. Proceeding with commit.${NC}"
